# Generated by Django 4.2 on 2023-10-23 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("UserRoleID", models.AutoField(primary_key=True, serialize=False)),
                ("RoleName", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("UserID", models.AutoField(primary_key=True, serialize=False)),
                ("Username", models.CharField(max_length=30)),
                ("Password", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=255)),
                ("FirstName", models.CharField(max_length=30)),
                ("LastName", models.CharField(max_length=30)),
                ("Phone", models.CharField(max_length=15, null=True)),
                (
                    "UserRoleID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.userrole"
                    ),
                ),
            ],
        ),
    ]
