# Generated by Django 4.2 on 2023-10-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="EventID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
